### ISSUE TITLE
[Design] API for CoinMarketCap and CoinGecko

### ISSUE THREAD

**Issue by msbrogli** [HathorNetwork/hathor-economics-api#1]
## Circulating Supply

The circulating supply will be calculated as `circulating_supply = mined_tokens + released_premined_tokens`, where:

- `mined_tokens`: amount of tokens given as rewards for mining (we cannot just do `64 * h`, where `h` is the height of the head of the best blockchain, because we must take reward halving in consideration).

- `released_premined_tokens`: amount of premined tokens released to the public, i.e., going to addresses that do not belong to one of the Hathor Labs' vault addresses.

## Implementation details

The implementation will be an AWS Lambda exposed by an AWS Gateway API with cache enabled.

The `released_premined_tokens` will be a constant in the lambda. So, we will need to update the lambda every time it changes.

### Alternative solutions (not used in this design)

Even though using a constant value for the `released_premined_tokens` requires updating the lambda every change, it is easier than querying the full node for the balance of a list of addresses. As this value will seldomly change, it won't be a problem. We also discarded using a Google Sheet to store the value.

## Endpoints

The Gateway API should have the following endpoints:

### `GET /status`

It must return the status of the economics API, including the latest time the values were updated and all pieces of information available in JSON format. All other endpoints should read the cache from this one and generate their correct response.

For example:

```json
{
  "latest_update": 1586564914,
  "backend": "https://node2.mainnet.hathor.network/",
  "total_supply": 1015000000,
  "circulating_supply": 35000000,
  "mined_tokens": 15000000,
  "released_premined_tokens": 20000000
}
```

### `GET /total-supply`

API endpoint that displays ONLY TOTAL SUPPLY as a NUMERICAL value. MUST be in this EXACT format - http://chainz.cryptoid.info/grs/api.dws?q=totalcoins. Total Supply refers to the # of coins in existence right now (minus any coins that have been verifiably burned.

### `GET /circulating-supply?decimals=true`

Circulating Supply API. Provide a URL that shows the number of circulating coins in real time with decimals, eg. 98,581,443.592800000000000000 eth

### `GET /circulating-supply`

Circulating Supply API (Totalbc). Provide a URL that shows the number of circulating coins in real time without decimals, eg. 98581443592800000000000000 eth

**Comment by obiyankenobi** [comment]
I think we should have a simpler design. We could have a google sheet with `released_premined_tokens` as it's easier to update.

We could then use AWS lambda for the API. It would query the spreadsheet (we can use some caching as this won't change that frequently) and also calculate the mined supply based on the time of the request. To be honest, I think we can consider one block every 30s instead of querying a fullnode for the height.

**Comment by pedroferreira1** [comment]
I don't think considering the vault addresses becomes that much complex. It's still really simple to update the numbers (just request the address history of the vault addresses and get the amount still there) and we have something much easier to keep updated.

About querying the fullnode for the height, I also don't mind considering the time only (right now it would give us an error of 100k HTR ~ 1500 blocks, which is not that much for me). However we already send the height of the full node in a ws message, we could just listen for this message and keep it updated.

**Comment by msbrogli** [comment]
I agree that using a Google Sheet would be easier to update, and I also like the idea of using AWS Lambda with Gateway API. The prices seem good as well (~$1 / million for the first 300 million requests). We can cache using both the Gateway API and the DynamoDB.

I don't think we should consider one block every 30 seconds. I think the API should return the correct value. This query is so cheap and simple for the full node that I think we should do it.

If you agree, I can update the design. @pedroferreira1 @obiyankenobi @jansegre

**Comment by obiyankenobi** [comment]
> The endpoints should never calculate the data in real time; they just read from cache. We should update the cache every X minutes and during initialization.

> I don't think we should consider one block every 30 seconds. I think the API should return the correct value.

I don't see how we'd return the correct value always if we cache results. I think it's better to use an estimate like 1 block every 30s than caching every X minutes.

**Comment by msbrogli** [comment]
@obiyankenobi For instance, block 00000000000000ea4f875376a1882e18011b466c14bdfacb5e85bec0b138f9d8 in Hathor's mainnet has timestamp 1586564914. Doing the math using the timestamp, it should have height `(1586564914 - 1578075305) / 30.0 = 282,986.97`. But its height is `281,840`. The absolute error is 1,147. It does not seem to be a big error, but it grows over time (with zero average).

The number of blocks found after `T` seconds follows a Poisson distribution with `lambda = T / 30`. So, variance grows linearly with `T`. In our case, `T` is always a big number.

**Comment by msbrogli** [comment]
I will update the design, so I'll keep a copy of the original proposal here:

## Circulating Supply

The circulating supply will be calculated as `circulating_supply = mined_tokens + released_premined_tokens`, where:

- `mined_tokens`: amount of tokens given as rewards for mining (we cannot just do `64 * h`, where `h` is the height of the head of the best blockchain, because we must take reward halving in consideration).

- `released_premined_tokens`: amount of premined tokens released to the public, i.e., going to addresses that do not belong to one of the Hathor Labs' vault addresses.

## Implementation details

The endpoints should never calculate the data in real time; they just read from cache. We should update the cache every X minutes and during initialization.

The configuration file must have the API endpoint of Hathor's full node, a list of one or more vault addresses, and a secret key for advancing the update, the hash of the genesis block.

To calculate the circulating supply, we must calculate the balance of all vault addresses.

## Endpoints

### `GET /status`

It must return the status of the economics API, including the latest time the values were updated and all values available.

### `POST /update`

An endpoint to advance the next update and run it now. It should return an error if the update is already running. It requires a secret key.

### `GET /total-supply`

API endpoint that displays ONLY TOTAL SUPPLY as a NUMERICAL value. MUST be in this EXACT format - http://chainz.cryptoid.info/grs/api.dws?q=totalcoins. Total Supply refers to the # of coins in existence right now (minus any coins that have been verifiably burned.

### `GET /circulating-supply?decimals=true`

Circulating Supply API. Provide a URL that shows the number of circulating coins in real time with decimals, eg. 98,581,443.592800000000000000 eth

### `GET /circulating-supply`

Circulating Supply API (Totalbc). Provide a URL that shows the number of circulating coins in real time without decimals, eg. 98581443592800000000000000 eth

**Comment by obiyankenobi** [comment]
> The absolute error is 1,147. It does not seem to be a big error, but it grows over time (with zero average).

I agree that we should not use the timestamp, then. I thought the error would be very small.

**Comment by msbrogli** [comment]
@obiyankenobi @pedroferreira1 @jansegre Can you review again, please?

**Comment by obiyankenobi** [comment]
I was thinking if it's worth having `released_premined_tokens` on an external spreadsheet. Since it's something that won't change often, we could have it directly on the lambda code. I know it's not the most elegant design, but it sure makes things very simple.

**Comment by pedroferreira1** [comment]
I still think that the best option is still to have the `vault_addresses` and we just check the amount with it but, since we are going with the spreadsheet and the solution is to use a specific cell to have the number, I agree with @obiyankenobi that we could use a fix number in the code. 

If the idea is to have some place with a fix number, having in the code is much better.

**Comment by msbrogli** [comment]
I've updated the design according to our discussion. Can you review again, please? @obiyankenobi @pedroferreira1 @jansegre

**Comment by obiyankenobi** [comment]
Looks good.

**Comment by pedroferreira1** [comment]
Good

**Comment by jansegre** [comment]
Good for me.
